### ISSUE TITLE
InsertBatch bug: Could not find table or view...

### ISSUE THREAD

**Issue by mikilion** [docevaad/Chain#172]
The "InsertBatch" command takes the table name from class instead of the "SqlServerObjectName" parameter when it is used like this:
```
IEnumerable<foo> entitiesList
dataSource.InsertBatch("TableName", entitiesList)...
```

**Comment by Grauenwolf** [comment]
This is a documentation/API discoverability problem.

InsertBatch is looking for the name of a user-defined type to use as a table-valued parameter. 

Proposed change:

1. Move the user defined type after the entitiesList parameter. That will make it clear that it isn't a table name.
2. Add the option to omit the user defined type. This would cause it to emit a series of inserts instead of one insert with a table-valued parameter. (Slower, but more convenient.)

No. 1 is a breaking change, but probably necessary in order for the API to make sense. 

No. 2 is much harder, as it would require rebuilding part of the data source to accept a linked list of commands. You would lose the ability to do things like echo back the newly inserted primary keys.

**Comment by Grauenwolf** [comment]
See #175 for part 2 of this ticket.
